title: "Crochet"
highlighter: rouge
markdown: kramdown

plugins:
  - jekyll-redirect-from

navigation:
  - text: Roadmap
    url: /roadmap/
    group: roadmap

  - text: Documentation
    url: /docs/
    group: external

  - text: Source Code
    url: https://github.com/qteatime/crochet
    group: external

defaults:
  - scope:
      path: _posts
      type: posts
    values:
      group: blog
      permalink: /articles/:year/:month/:title/
