name: publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.99.0
        with:
          ruby-version: '2.7.5'

      - name: Setup Python
        uses: actions/setup-python@v2.3.2
        with:
          python-version: '3.x'

      - run: |
          bundle install
          
      - run: |
          git submodule init
          
      - run: |
          make build
          touch _site/docs/.nojekyll
          cp CNAME _site/docs/CNAME
          mv _site/docs new-docs
          git checkout gh-pages
          rm -rf docs
          mv new-docs docs
          if [ -n "$(git status --porcelain)" ]; then
            git add docs
            git config --global user.name "Quil, but a robot"
            git config --global user.email "robotlolita@users.noreply.github.com"
            git commit -m "Publish website"
            git push
          fi
